### PR TITLE
Update sample data.

### LINKED ISSUE #207: QC: Update data in data-raw with all KRIs
## QC Details
Ideally use a gsm workflow to build the sample data. Might need to create a new workflow for this to preserve the input datasets for the Participant Details tab.

### PR DESCRIPTION
**Pull request by jonthegeek**
## Overview
Update sample data to include all KRIs except kri0012.

## Test Notes/Sample Code
I haven't updated the participant data, so we still have just the 4 input domains (in an older format). I hope to fix this before I mark this ready for review.

There's also an issue where I get into a loop after selecting a site + KRI (via the table on tab 1) and then a participant. I suspect it has something to do with something not fully loading, but I can't replicate it consistently, and so far nothing is showing up in any logs.

## Connected Issues

- Closes #207.
- Covers most of #211.

### CODE REVIEW

**Comment by lauramaxwell** [comment]
@jonthegeek based on the PR note above, are you still planning on adding the additional domains to the Participant tab, or am i misreading that?

**Comment by jonthegeek** [comment]
> @jonthegeek based on the PR note above, are you still planning on adding the additional domains to the Participant tab, or am i misreading that?

Oops! I updated those 4, so that note is out of date.... But let me take a stab at finishing the others today. I think I was cranky yesterday from fighting the bug and just wanted to be done 🙃

**Comment by jonthegeek** [comment]
Still to-do: I should almost definitely update the names of the domain dfs to be more user-facing.

**Review by lauramaxwell — APPROVED** [review]
looks good- the `userFacing` workflows are a nice way to use `Ingest()` once we ensure dates come back in the correct format!

**Pull request merged**
