### PR TITLE
Differentiate single- and cross-snapshot results data.

### PR DESCRIPTION
**Pull request by samussiah**
## Connected Issues

- Closes #XXX

### CODE REVIEW

**Comment by jonthegeek** [comment]
Do the snapshot filter once here: https://github.com/Gilead-BioStats/gsm.app/blob/0b48f1ac05141b96fef4ff1b78bbaf0bbf32429d/R/run_gsm_app.R#L36-L37

Then it will be fixed everywhere.

**Comment by samussiah** [comment]
> Do the snapshot filter once here:
> 
> https://github.com/Gilead-BioStats/gsm.app/blob/0b48f1ac05141b96fef4ff1b78bbaf0bbf32429d/R/run_gsm_app.R#L36-L37
> 
> Then it will be fixed everywhere.

My only concern is the time series needs the longitudinal results.  It might be best to have separate single- and multi-snapshot data frames.

**Comment by samussiah** [comment]
I don't have a great idea for handling the list of study attributes in the study information card, other than to throw it in a configuration argument, or simply displaying all study attributes in `dfGroups`.

**Comment by jonthegeek** [comment]
> My only concern is the time series needs the longitudinal results. It might be best to have separate single- and multi-snapshot data frames.

Fair enough. Add the filtered DF to the top of the server function, outside a reactive. It doesn't change (without a redeployment), so there's no need to make that part reactive. I can handle this momentarily (once I switch to my Atorus laptop) if you'd like.

**Review by jonthegeek — APPROVED** [review]
I updated things to use the `gsm::FilterByLatestSnapshotDate()` function, and to minimize the number of times that the filter happens without over-abstracting. If the app ends up slow with real data, we can optimize this a little more, but I'm trying to tweak modules toward accepting the standard inputs and then dealing with them internally... so you mostly did the right thing 😊

**Comment by jonthegeek** [comment]
> I don't have a great idea for handling the list of study attributes in the study information card, other than to throw it in a configuration argument, or simply displaying all study attributes in `dfGroups`.

Yeah, I don't love the study info card at all yet. I'm fine with leaving it like this for this release, but in the future we'll probably use whatever's in dfGroups at the Study level (and filter things out of there if we don't want it in our deployed versions).

**Pull request merged**
