### PR TITLE
Implement metric charts as modules

### LINKED ISSUE #309: Feature: mod_BarChart_*
## Feature Details
Replace the `gsm::Widget_BarChartOutput()`s on the two Bar Chart tabs on Metric Details with a proper module & shiny input.

## Possible Implementation
This should be very, very similar to the Scatter Plot tab.

### LINKED ISSUE #310: Feature: mod_TimeSeries_*
## Feature Details
Replace the `gsm::Widget_TimeSeriesOutput()`s on the Time Series tab on Metric Details with a proper module & shiny input.

## Possible Implementation
This should be very, very similar to the Scatter Plot tab.

### PR DESCRIPTION
**Pull request by jonthegeek**
## Overview
Removed redundant R code.

Cleaned up shared JavaScript.

Implemented Widget_BarChart() & mod_BarChart_*().

## Test Notes/Sample Code
In theory it should look almost identical to how it was (except now I'm showing thresholds where appropriate). You can deselect on Bar Chart and Time Series tabs on Metric Details (and those deselects are reflected everywhere else); before this fix deselecting didn't work.

## Connected Issues

- Closes #309.
- Closes #310.

### CODE REVIEW

**Review by lauramaxwell — CHANGES_REQUESTED** [review]
Working well on the bar chart, but the deselect on the time series chart isn't working for me.

**Comment by jonthegeek** [comment]
> Working well on the bar chart, but the deselect on the time series chart isn't working for me.

It never has (see for example https://openrbqm.shinyapps.io/gsm-app/). As far as I can tell, the widget doesn't support... well darn, I think I can make it work, now that I think about it 🙃
Fixing!

**Comment by jonthegeek** [comment]
@lauramaxwell Darnit, I can't get it to register a click event for deselect. It isn't that my click callback isn't updating things properly; I can't get it to call the clickCallback in that situation.

@samussiah I can't figure out what would cause this to not work. It feels like it's in the vicinity of `rmb-viz/src/util/onClick.js` line 7+; the selected point doesn't give an interaction icon on hover, so it doesn't think it's clickable at that time. It isn't a HUGE issue, but... should I file an issue over in rbm-viz? And can you help me figure out where to tell it that it's clickable?

**Comment by samussiah** [comment]
> @lauramaxwell Darnit, I can't get it to register a click event for deselect. It isn't that my click callback isn't updating things properly; I can't get it to call the clickCallback in that situation.
> 
> @samussiah I can't figure out what would cause this to not work. It feels like it's in the vicinity of `rmb-viz/src/util/onClick.js` line 7+; the selected point doesn't give an interaction icon on hover, so it doesn't think it's clickable at that time. It isn't a HUGE issue, but... should I file an issue over in rbm-viz? And can you help me figure out where to tell it that it's clickable?

I'm seeing the same thing - the highlighted point isn't responding to click events ([issue 1](https://github.com/Gilead-BioStats/rbm-viz/issues/420)).  The other nice-to-have is a aligning the time series update methods with the bar chart and scatter plot update methods: `updateSelectedGroupIDs` vs `updateConfig` ([issue 2](https://github.com/Gilead-BioStats/rbm-viz/issues/421)).

**Comment by jonthegeek** [comment]
> I'm seeing the same thing - the highlighted point isn't responding to click events ([issue 1](https://github.com/Gilead-BioStats/rbm-viz/issues/420)). The other nice-to-have is a aligning the time series update methods with the bar chart and scatter plot update methods: `updateSelectedGroupIDs` vs `updateConfig` ([issue 2](https://github.com/Gilead-BioStats/rbm-viz/issues/421)).

Excellent, yes! I have a special "If this method exists, use it, if this other method exists, use that" in the code I'm experimenting with.

**Review by lauramaxwell — APPROVED** [review]

**Pull request merged**
